SET SERVEROUTPUT ON
DECLARE
  v_owners       SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('CMS_NOTIFICATION','GO_CONNECT','CMS_GLOBAL','CMS_AUDIT','CMS_CARD','CMS_CARD_MGMT','CMS_SUPPORT','CMS_USER_ADMIN','CMS_PROGRAM_CFG');
  v_owner        VARCHAR2(500);
  v_table_name   VARCHAR2(500);
  v_full_table   VARCHAR2(500);
  v_column_name  VARCHAR2(500);
  v_max_id       NUMBER;
  v_count        NUMBER;
  v_is_identity  VARCHAR2(3);
  v_is_pk_column NUMBER;
BEGIN
  FOR i IN 1 .. v_owners.COUNT LOOP
    v_owner := v_owners(i);

    FOR tbl IN (
      SELECT atb.owner, atb.table_name
      FROM all_tables atb 
      JOIN all_tab_columns ac 
        ON atb.table_name = ac.table_name AND atb.owner = ac.owner
      WHERE atb.owner = UPPER(v_owner)
        AND ac.column_name = ac.table_name || '_ID'
    ) LOOP
      v_table_name := tbl.table_name;
      v_column_name := v_table_name || '_ID';
      v_full_table := tbl.owner || '.' || tbl.table_name;

      BEGIN
        -- Check if the column is part of the primary key
        SELECT COUNT(*) INTO v_is_pk_column
        FROM all_constraints c
        JOIN all_cons_columns cc
          ON c.constraint_name = cc.constraint_name AND c.owner = cc.owner
        WHERE c.constraint_type = 'P'
          AND c.owner = UPPER(v_owner)
          AND c.table_name = UPPER(v_table_name)
          AND cc.column_name = UPPER(v_column_name);

        IF v_is_pk_column = 0 THEN
          DBMS_OUTPUT.PUT_LINE('? SKIPPED: ' || v_full_table || ' - ' || v_column_name || ' is NOT part of PK');
          CONTINUE;
        END IF;

        -- Check if table has rows
        EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || v_full_table || ' WHERE ROWNUM = 1'
          INTO v_count;

        -- Check if column is identity
        BEGIN
          SELECT identity_column
          INTO v_is_identity
          FROM all_tab_columns
          WHERE owner = UPPER(v_owner)
            AND table_name = UPPER(v_table_name)
            AND column_name = UPPER(v_column_name);

          IF v_is_identity = 'YES' THEN
            -- Get max value
            EXECUTE IMMEDIATE 'SELECT NVL(MAX(' || v_column_name || '), 0) FROM ' || v_full_table
              INTO v_max_id;

            -- Reset identity
            EXECUTE IMMEDIATE 
              'ALTER TABLE ' || v_full_table || 
              ' MODIFY ' || v_column_name || 
              ' GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || ')';

            DBMS_OUTPUT.PUT_LINE('? ✅ Reset identity on ' || v_full_table || '.' || v_column_name || 
                                 ' to START WITH ' || (v_max_id + 1));
          ELSE
            DBMS_OUTPUT.PUT_LINE('? ⚠️ Column ' || v_column_name || ' is not identity on ' || v_full_table);
          END IF;

        EXCEPTION
          WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('? ❌ Column ' || v_column_name || ' not found in ' || v_full_table);
          WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('? ❌ Error checking identity for ' || v_full_table || ': ' || SQLERRM);
        END;

      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('? ❌ Error processing ' || v_full_table || ': ' || SQLERRM);
      END;
    END LOOP;
  END LOOP;
END;
/